# Generated by Django 5.1.10 on 2026-10-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_churchsetup_onboardingprofile'),
        ('events', '0003_eventannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_times', to='accounts.church')),
            ],
            options={
                'ordering': ('weekday', 'time', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='service_weekday_valid'), models.UniqueConstraint(fields=('church', 'weekday', 'time', 'location'), name='unique_service_time')],
            },
        ),
    ]
