# Generated by Django 5.1.10 on 2026-06-30 17:16

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('tithe', 'Dizimo'), ('offering', 'Oferta'), ('campaign', 'Campanha'), ('missions', 'Missoes'), ('event', 'Evento'), ('other', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('needs_review', 'Precisa Revisao')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='accounts.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contributions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribuicao',
                'verbose_name_plural': 'Contribuicoes',
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.finance.models.contribution_attachment_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.contribution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contribution_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Contribuicao',
                'verbose_name_plural': 'Anexos de Contribuicao',
            },
        ),
    ]
