# Generated by Django 5.1.10 on 2026-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
