# Generated by Django 5.1.10 on 2026-09-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_contribution_review_notes'),
        ('finance', '0003_contribution_financial_link'),
    ]

    operations = [
    ]
