FROM nginxinc/nginx-unprivileged:1.28-alpine
ARG APP_REVISION=unknown
LABEL org.opencontainers.image.revision=$APP_REVISION
COPY deploy/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY mobile/dist/ /usr/share/nginx/html/
EXPOSE 8080
