# Generated by Django 5.1.10 on 2026-08-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Posicao na ordem do culto.')),
                ('item_type', models.CharField(choices=[('song', 'Musica'), ('moment', 'Momento'), ('reading', 'Leitura'), ('other', 'Outro')], default='song', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('song_key', models.CharField(blank=True, help_text='Ex: G, Am, D#', max_length=12, verbose_name='Tom')),
                ('reference_url', models.URLField(blank=True, help_text='Cifra, letra ou video de referencia.', verbose_name='Link')),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='accounts.church')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Item da Escala',
                'verbose_name_plural': 'Itens da Escala',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
