# Generated by Django 5.1.10 on 2026-09-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_ministry_coordinators'),
        ('schedules', '0004_personalcommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ministry',
            field=models.ForeignKey(blank=True, help_text='Ministerio responsavel pela escala. Coordenador so administra o do seu ministerio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='ministries.ministry'),
        ),
    ]
