# Generated by Django 5.1.10 on 2026-09-15 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pastor', 'Pastor'), ('secretary', 'Secretaria'), ('treasurer', 'Tesoureiro'), ('cell_leader', 'Lider de Celula'), ('coordinator', 'Coordenador'), ('member', 'Membro')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Papel adicional',
                'verbose_name_plural': 'Papeis adicionais',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment')],
            },
        ),
    ]
