# Generated by Django 5.1.10 on 2026-10-08 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSendLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField()),
                ('last_sent', models.DateTimeField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('purpose', models.CharField(default='login', max_length=8)),
                ('code_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(null=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('proof_digest', models.CharField(blank=True, max_length=64)),
                ('proof_expires_at', models.DateTimeField(null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('church', 'phone'), name='unique_church_whatsapp')],
            },
        ),
    ]
