# Generated by Django 5.1.10 on 2026-10-09 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_whatsappsendlimit_whatsappchallenge_whatsappidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('team_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='accounts.church')),
                ('church_reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_reviews', to=settings.AUTH_USER_MODEL)),
                ('team_reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('discovering', 'Estou conhecendo a igreja'), ('attending', 'Já frequento, mas ainda não sou membro'), ('member', 'Já sou membro')], max_length=16)),
                ('step', models.CharField(default='welcome', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_dismissed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
