# Generated by Django 5.1.10 on 2026-06-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('visitors_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reuniao de Celula',
                'verbose_name_plural': 'Reunioes de Celula',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('meeting_day', models.CharField(blank=True, max_length=40)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('assistant_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_cells', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='accounts.church')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Celula',
                'verbose_name_plural': 'Celulas',
            },
        ),
        migrations.CreateModel(
            name='CellAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_attendances', to='accounts.church')),
            ],
            options={
                'verbose_name': 'Presenca de Celula',
                'verbose_name_plural': 'Presencas de Celula',
            },
        ),
    ]
