# Generated by Django 5.1.10 on 2026-06-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cells', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cellattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_attendances', to='members.member'),
        ),
        migrations.AddField(
            model_name='cellmeeting',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cells.cell'),
        ),
        migrations.AddField(
            model_name='cellmeeting',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_meetings', to='accounts.church'),
        ),
        migrations.AddField(
            model_name='cellmeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_meetings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cellattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cells.cellmeeting'),
        ),
        migrations.AlterUniqueTogether(
            name='cellattendance',
            unique_together={('meeting', 'member')},
        ),
    ]
