# Generated by Django 5.1.10 on 2026-06-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='accounts.church')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('visitor', 'Visitante'), ('inactive', 'Inativo'), ('transferred', 'Transferido'), ('deceased', 'Falecido')], default='active', max_length=20)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='cells.cell')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.church')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('spouse', 'Conjuge'), ('child', 'Filho(a)'), ('parent', 'Pai/Mae'), ('guardian', 'Responsavel'), ('sibling', 'Irmao(a)'), ('other', 'Outro')], max_length=20)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='accounts.church')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='members.family')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='members.member')),
                ('related_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='members.member')),
            ],
            options={
                'verbose_name': 'Relacionamento Familiar',
                'verbose_name_plural': 'Relacionamentos Familiares',
                'unique_together': {('family', 'member', 'related_member', 'relationship_type')},
            },
        ),
    ]
