# Generated by Django 5.x on 2026-09-17.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userroleassignment"),
        ("members", "0002_memberupdaterequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberLinkRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_email", models.EmailField(max_length=254)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("approved", "Aprovada"), ("rejected", "Rejeitada")], default="pending", max_length=20)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_member", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="link_requests", to="members.member")),
                ("church", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_link_requests", to="accounts.church")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_member_link_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_link_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Solicitacao de vinculo cadastral",
                "verbose_name_plural": "Solicitacoes de vinculo cadastral",
                "ordering": ["-created_at"],
            },
        ),
    ]
